set SPARK_EXECUTOR_CORES=2
set SPARK_WORKER_INSTANCES=2
set SPARK_WORKER_CORES=4
set SPARK_WORKER_MEMORY=2g
set SPARK_MASTER_PORT=7077
set SPARK_MASTER_WEBUI_PORT=8080
set SPARK_WORKER_WEBUI_PORT=8081
set SPARK_PUBLIC_DNS="localhost"